spring:
  application:
    name: SkillForge
  data:
    web:
      pageable:
        one-indexed-parameters: true # Use one-indexed parameters for pagination

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    url: jdbc:postgresql://localhost:5432/skillforge_db
    username: postgres
    password: 1084

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



server:
  port: 8080

jwt:
  secret: ${SECRET_KEY:defaultSecretKey}
  access-token-validity-in-seconds: 8640000 # 100 days
  refresh-token-validity-in-seconds: 864000000 # 1000 days

bunny:
  stream:
    access-key: ${BUNNY_API_KEY:defaultBunnyApiKey}
    library-id: 469408
    base-url: "https://video.bunnycdn.com"
    bunny-cdn-key: ${BUNNY_CDN_KEY:defaultBunnyCdnKey}
    bunny-cdn-host: "vz-11106c72-014.b-cdn.net"
    bunny-auth-key: "7aec43d5-f3be-440f-b740-55fd5e455cf4"


