spring.application.name=SkillForge

spring.datasource.url=jdbc:postgresql://localhost:5432/skillforge_db
spring.datasource.username=postgres
spring.datasource.password=1084


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========== Server Config ==========
server.port=8080
